### PR TITLE
Fetch icons from https://fonts.google.com/metadata/icons

### PR DESCRIPTION
**Pull request by andrewkshim**
Hi @stramel 👋 First thanks for putting this project together.

I use [`styled-icons`], and I was upgrading from `styled-icons@7.14.0` to the latest version and noticed that the [`ContentPaste`] Material icon (among others) is no longer available.

The issue appears to be in this package. Specifically, the manifest at https://material.io/tools/icons/static/data.json does not contain a comprehensive inventory of the icons. Inspecting the network traffic on https://material.io/resources/icons, it looks like latest manifest is available at https://fonts.google.com/metadata/icons.

I went ahead and updated the `download.js` script to fetch the icons using the latest manifest. Full details of this PR:

- Fetches manifest from https://fonts.google.com/metadata/icons
- Updates script to handle new manifest schema
- Updates script to print the diff between the old/new manifests
  - Due to a change in the manifest schema, the previous version check mechanism is no longer relevant (notably, each icon has its own version)
  - Because of this change, you'll need to remove the existing `manifest.json` before running the updated script

With these updates, the number of icons downloaded increased from ~5k to ~6k.

To reduce the size of this PR and make the diff easier to read, I excluded the changes to the `manifest.json` and `icons/` files. If things look good to you, you'll need to re-run the download script before publishing the next release. Please let me know if you have any questions/comments, happy to address any feedback. Thanks!

[`styled-icons`]:https://github.com/jacobwgillespie/styled-icons
[`ContentPaste`]:https://material.io/resources/icons/?icon=content_paste&style=baseline

### CODE REVIEW

**Comment by stramel** [comment]
Thanks for the PR! I will check this out today or tomorrow and provide feedback.

**Comment by stramel** [comment]
LGTM! I appreciate the PR! Going to merge it and then do some clean up. Hope to have the new icons published soon.

**Comment by andrewkshim** [comment]
Sounds good, thanks @stramel 👍

**Comment by stramel** [comment]
@andrewkshim New Icons are published! https://github.com/stramel/material-design-icons-updated/tree/v5.0.0

Thank you for the hard work!

**Pull request merged**
